### ISSUE TITLE
Could you please provide detail step by step guide to run project on docker?

### ISSUE THREAD

**Issue by TranNgocKhoa** [numery009/SpringBoot-SpringCloud-Docker#1]
Hello,
I found your project on Github and it awesome. I'd like to run it on Docker because I'm learning about this too.
But I'm a newbie in microservices. Could you give me any documents or update a tutorial in readme file?

Thank you so much!

**Comment by numery009** [comment]
Hi, 

I have updated the "Run this project" on the README.md file.

Thanks

**Comment by TranNgocKhoa** [comment]
Thank you so much! I'm learning through your code

**Comment by TranNgocKhoa** [comment]
If I build Docker images by myself, how can I do that?
