### ISSUE TITLE
Should we save netflix-eureka-naming-server config file in remote repository?

### ISSUE THREAD

**Issue by TranNgocKhoa** [numery009/SpringBoot-SpringCloud-Docker#2]
I noticed that some microservices project on Github save their config files like `application.properties` on a remote repository and fetch data through **Config Server**, even **Naming-Server**.
So I'm curious about why don't you do that?

**Comment by numery009** [comment]
I did it on customer-service-mysql micro-services. Fetching the database configuration from the config server.

https://github.com/numery009/Spring-Boot-And-Spring-Cloud/blob/master/customer-service-mysql/src/main/resources/bootstrap.properties

These are the sample micro-services. I have used varieties of Spring-Cloud feature on all the services in various way. 

But in the production level we should use Config Server to fetch the properties of our micro-services.
